### ISSUE TITLE
[BUG] Conda activate not working on macOS

### ISSUE THREAD

**Issue by pcruzastro** [escape2020/school2021#32] opened 2021-06-07 09:39 UTC
**Describe the bug**

Good morning!
I’m following the instructions at https://github.com/escape2020/school2021 and I am not able to solve a problem.
When I run:

conda activate eschool2021

I receive the following:

macbook | school2021 # conda activate eschool2021

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

**Screenshots**

![condaerror](https://user-images.githubusercontent.com/72438908/120994538-db130780-c784-11eb-865f-a1d36402385f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] -> 
 - `conda --version` -> conda 4.10.1
 - `python --version` -> Python 3.8.10

**Additional context**

 I tried to reopen my terminal and it did not solve the problem.
 And I also updated my conda version (see the version used above).

**Comment by maxnoe** [comment] 2021-06-07 09:43
Are you on a recent macOS? I.e. have the zsh as shell? You can check with
```
$ echo $SHELL
```

If this shows `zsh`, can you try running:

```
$ conda init zsh
```

and then close and reopen your terminal and try to run the `conda activate eschool2021` command again?

**Comment by pcruzastro** [comment] 2021-06-07 09:50
No, sorry! I failed to put my OS version. I using El Captain (10.11.6).
My shell is bash:

# echo $SHELL
/bin/bash

And, when I try 
$ conda init bash
I get:

![condaerror2](https://user-images.githubusercontent.com/72438908/120996433-98eac580-c786-11eb-8c0f-ff15ed14e730.png)

**Comment by tamasgal** [comment] 2021-06-07 09:53
I fear El Capitan will be a tough one to get working with Python 3.9 and all the required versions.

What is your hardware? Any chance that you can spend a few hours to upgrade your macOS to the latest possible version?

**Comment by adonath** [comment] 2021-06-07 09:58
This is a related issue I found in the conda issue tracker: https://github.com/conda/conda/issues/7980

**Comment by pcruzastro** [comment] 2021-06-07 10:00
Sorry but I am afraid I won't be able to upgrade my OS.
I do use without any problem Jupiter notebooks. Maybe I will leave it this way then and see how it goes - assuming I will be able to follow the tutorials only via notebooks.

Thank you anyway!

**Comment by tamasgal** [comment] 2021-06-07 10:02
I see. Then I'd suggest -- as you wrote -- to go ahead and whenever you hit a "xyz: module not found", just try to install it with e.g. `pip install xyz`.

**Comment by pcruzastro** [comment] 2021-06-07 10:02
I will try to use the solution for bash, then. Let's see how it goes.
Thank you @adonath!

**Comment by pcruzastro** [comment] 2021-06-07 10:03
Great! Thank you for the tip, @tamasgal !

**Comment by maxnoe** [comment] 2021-06-07 10:06
Can you open your `.bash_profile` in a text editor and check if it contains anything from `conda`?

If not, just adding these two lines should  fix it:

```
eval "$(conda shell.bash hook)"
```


if you see stuff related to conda, try commenting it out and adding that line. After that, opening a new terminal and doing `conda activate <env name>` should work.

**Comment by pcruzastro** [comment] 2021-06-07 10:17
Yes @maxnoe, I did check my .bash_profile and there was some conda related lines.
But even having commented them and adding your suggestion, I still get the same thing.

**Comment by maxnoe** [comment] 2021-06-07 10:24
@pcruzastro I think at this point, we should meet in the gather town to see how we can fix this.

**Comment by pcruzastro** [comment] 2021-06-07 10:26
@maxnoe sure!

**Comment by maxnoe** [comment] 2021-06-07 11:42
We found out that this was caused by a messed up shell setup. @pcruzastro was starting a `csh` in `.bash_profie`, which make conda think it was inside a bash when it was really in a `csh`.

Fixed by making the default shell `csh` and putting the configuration for `csh` into `~/.cshrc`.

**Closed by maxnoe** 2021-06-07 11:42 UTC
Labels: bug
